<?php
/**
 * @file 
 * Views timeline Integration, Theming, and libraries
 */

/**
 * Implements hook_views_api().
 * Will look for views plugin files in /sites/<your site>/modules/views_timeline.views.inc
 */
function views_timeline_views_api() {
  return array(
    'api' => '3',
    'path' => drupal_get_path('module', 'views_timeline'),
  );
}

/**
 * Implements hook_ctools_plugin_directory().
 *
 * Plugin integration for date sources, image sources and timeline themes.
 */
function views_timeline_ctools_plugin_directory($module, $plugin) {
	if ($module == 'views_timeline') {
		return 'plugins/' . $plugin;
	}
}

/**
 * Implements hook_ctools_plugin_type().
 */
function views_timeline_ctools_plugin_type() {
	return array(
// 			'date_sources' => array(),
			'text_sources' => array(),
			'image_sources' => array(),
	);
}